spring:
  application:
    name: Biblioteca
  datasource:
      url: jdbc:postgresql://localhost:5432/Biblioteca
      username: postgres
      password: 364bFBkJ6w12
      driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: seu-email@gmail.com
    password: sua-senha-de-app
    properties:
        mail:
            smtp:
                auth: true
                starttls:
                    enable: true


api.security:
  token:
    secret: mySecretKey
#    expiration: 3600000